server:
  port: 18082
spring:
  servlet:
    multipart:
      max-file-size: 10MB #max-file-size是单个文件大小
      max-request-size: 10MB #max-request-size是设置总上传的数据大小
  application:
    name: changgou-file-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8828